baseurl      = "https://madsandersen.net"
title        = "testing"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Homepage"
  keywords = "homepage"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"

  footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
  footerRight = " "

  [params.portrait]
    path     = "/img/profile-square.jpg"
    alt      = "Portrait"
    maxWidth = "200px"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:bjerre+website@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/Mads-Andersen"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mads-bjerregaard-andersen-59ab27a4/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Mads Andersen"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "home/mads-andersen"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
    [[menu.main]]
      identifier = "resume.md"
      name       = "Resume"
      url        = "/resume"
      
    [[menu.main]]
      identifier = "me.md"
      name       = "Me"
      url        = "/me"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
name = "mydeployment"
URL = "s3://madsandersen.net?region=eu-west-1"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://<Bucket Name>?region=<AWS region>"
